// SPDX-License-Identifier: AGPL-3.0-or-later
// Reserved-word classes of the 4.0 grammar; `node words.js` writes them to src/words.h for the scanner.

const reserved = require('../../tools/language/keywords.json');

const STATEMENT = ['if', 'else', 'for', 'while', 'break', 'continue', 'include', 'let', 'fn', 'global',
  'return', 'null', 'in', 'to', 'step', 'true', 'false', 'function'];
const DIRECTIVE = ['append', 'breakpoint', 'case', 'declare', 'deprecated', 'elseif', 'end', 'fclose', 'fopen',
  'ifdef', 'ifndef', 'local', 'macro', 'read', 'switch', 'undef', 'write'];
const COLOUR = ['rgb', 'rgbf', 'rgbt', 'rgbft', 'srgb', 'srgbf', 'srgbt', 'srgbft'];
const COLOR = ['color', 'colour'];
const CHANNEL = ['alpha', 'blue', 'filter', 'gray', 'green', 'grey', 'red', 'transmit'];
const VALUE_OTHER = ['t', 'u', 'v', 'str', 'vstr', 'concat', 'chr', 'datetime', 'substr', 'strlwr', 'strupr',
  'sqr', 'array', 'range', 'debug', 'warning', 'error', 'filter'];

const VALUE = [...new Set([
  ...reserved.filter((w) => w.category === 'float' || w.category === 'vector').map((w) => w.word),
  ...VALUE_OTHER,
])].filter((w) => !STATEMENT.includes(w)).sort();
const KEYWORD = reserved.map((w) => w.word).filter((w) => !STATEMENT.includes(w) && !DIRECTIVE.includes(w) &&
  !VALUE.includes(w) && !COLOUR.includes(w) && !COLOR.includes(w) && !CHANNEL.includes(w)).sort();

module.exports = { KEYWORD, VALUE, COLOUR, COLOR, CHANNEL };

if (require.main === module) {
  const list = (name, words) => `static const char *const ${name}[] = {\n${words.map((w) => `  "${w}",`).join('\n')}\n};\n`;
  const sorted = (words) => [...words].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  require('fs').writeFileSync(`${__dirname}/src/words.h`, '// Generated by words.js from tools/language/keywords.json.\n' +
    list('KEYWORDS', sorted(KEYWORD)) + list('BUILTINS', sorted(VALUE)) + list('COLOURS', sorted(COLOUR)) +
    list('COLORS', sorted(COLOR)) + list('CHANNELS', sorted(CHANNEL)));
}
