#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
// Generates pov4.json: a documented, tool-consumable grammar for the 4.0 scene language,
// normalized from the tree-sitter grammar committed in libraries/tree-sitter-pov4.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

const here = dirname(fileURLToPath(import.meta.url));
const tsGrammarPath = join(here, '../../../libraries/tree-sitter-pov4/src/grammar.json');
const outPath = join(here, 'pov4.json');

const strip = (node) => {
    switch (node.type) {
        case 'STRING':      return { t: 'str', v: node.value };
        case 'PATTERN':     return { t: 're', v: node.value };
        case 'SYMBOL':      return { t: 'sym', name: node.name };
        case 'BLANK':       return { t: 'blank' };
        case 'SEQ':         return { t: 'seq', of: node.members.map(strip) };
        case 'CHOICE':      return { t: 'choice', of: node.members.map(strip) };
        case 'REPEAT':      return { t: 'repeat', of: strip(node.content) };
        case 'REPEAT1':     return { t: 'repeat1', of: strip(node.content) };
        case 'OPTIONAL':    return { t: 'opt', of: strip(node.content) };
        case 'PREC':        return { t: 'prec', v: node.value, of: strip(node.content) };
        case 'PREC_LEFT':   return { t: 'prec', kind: 'left', v: node.value, of: strip(node.content) };
        case 'PREC_RIGHT':  return { t: 'prec', kind: 'right', v: node.value, of: strip(node.content) };
        case 'PREC_DYNAMIC':return { t: 'prec', kind: 'dynamic', v: node.value, of: strip(node.content) };
        case 'TOKEN':       return { t: 'token', of: strip(node.content) };
        case 'IMMEDIATE_TOKEN': return { t: 'token', immediate: true, of: strip(node.content) };
        case 'ALIAS':       return { t: 'alias', of: strip(node.content), name: node.named ? node.value : `"${node.value}"` };
        case 'FIELD':       return { t: 'field', name: node.name, of: strip(node.content) };
        default: throw new Error(`unknown grammar node type ${node.type}`);
    }
};

const alts = (rule) => (rule.type === 'CHOICE' ? rule.members : [rule]);
const members = (names, grammar, seen = new Set()) => {
    const out = [];
    for (const name of names) {
        if (seen.has(name) || !grammar.rules[name]) continue;
        seen.add(name);
        const rule = grammar.rules[name];
        for (const alt of alts(rule))
            for (const leaf of collectSyms(alt)) {
                if (grammar.rules[leaf] && !out.includes(leaf)) out.push(leaf);
                if (grammar.rules[leaf]) out.push(...members([leaf], grammar, seen).filter((m) => !out.includes(m)));
            }
    }
    return out;
};
const collectSyms = (node, out = []) => {
    if (node.type === 'SYMBOL') out.push(node.name);
    for (const key of ['content', 'members', 'alternative']) if (node[key]) collectSyms(node[key], out);
    return out;
};

const grammar = JSON.parse(readFileSync(tsGrammarPath, 'utf8'));
const isLexical = (rule) => !alts(rule).some((alt) => JSON.stringify(alt).includes('"type":"SYMBOL"'));
const lexical = Object.entries(grammar.rules).filter(([, r]) => isLexical(r)).map(([name]) => name);

const document = {
    format: 'pov4-grammar/1',
    comment: 'Machine-readable grammar of the POV-Ray 4.0 scene language (.pov4). Generated by tools/language/grammar/extract.mjs; regenerate rather than edit. Node kinds: seq/choice/repeat/repeat1/opt/prec/alias/field/token wrapper nodes plus leaves str (literal), re (regex), sym (rule reference), blank.',
    name: grammar.name,
    word: grammar.word,
    externals: grammar.externals.map((e) => e.name),
    extras: grammar.extras.map((e) => strip(e)),
    conflicts: grammar.conflicts.map((c) => c.map((s) => s.name)),
    inline: (grammar.inline ?? []).filter((n) => n !== 'end'),
    supertypes: (grammar.supertypes ?? []).map((s) => s.name),
    wordClasses: {
        comment: 'Reserved-word classes driving the contextual scanner (libraries/tree-sitter-pov4/words.js).',
        ...require('./tree-sitter-classes.cjs'),
    },
    groups: {
        statements: members(['_statement'], grammar).filter((n) => !n.startsWith('_')),
        expressions: members(['_expression'], grammar).filter((n) => !n.startsWith('_')),
        postfix: members(['_postfix'], grammar).filter((n) => !n.startsWith('_')),
        primary: members(['_primary'], grammar).filter((n) => !n.startsWith('_')),
        lexical,
    },
    rules: Object.fromEntries(Object.entries(grammar.rules).map(([name, rule]) => [name, {
        hidden: name.startsWith('_') || undefined,
        productions: alts(rule).map(strip),
    }])),
};

writeFileSync(outPath, JSON.stringify(document, null, 1) + '\n');
console.log(`pov4.json: ${Object.keys(document.rules).length} rules, ${document.groups.statements.length} statements, ${document.groups.expressions.length} expressions`);
