// SPDX-License-Identifier: AGPL-3.0-or-later
// Generates the VS Code extension's TextMate grammar and block tables from the language sources.
// Run from anywhere: node tools/language/vscode.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const reserved = JSON.parse(readFileSync(join(root, 'tools/language/keywords.json'), 'utf8'));
const blockDoc = JSON.parse(readFileSync(join(root, 'tools/language/grammar/blocks.json'), 'utf8'));

// Word classes mirror libraries/tree-sitter-pov4/words.js.
const STATEMENT = ['if', 'else', 'for', 'while', 'break', 'continue', 'include', 'let', 'fn', 'global',
    'return', 'null', 'in', 'to', 'step', 'true', 'false', 'function'];
const DIRECTIVE = ['append', 'breakpoint', 'case', 'declare', 'deprecated', 'elseif', 'end', 'fclose', 'fopen',
    'ifdef', 'ifndef', 'local', 'macro', 'read', 'switch', 'undef', 'write'];
const COLOUR = ['rgb', 'rgbf', 'rgbt', 'rgbft', 'srgb', 'srgbf', 'srgbt', 'srgbft'];
const COLOR = ['color', 'colour'];
const CHANNEL = ['alpha', 'blue', 'filter', 'gray', 'green', 'grey', 'red', 'transmit'];
const VALUE_OTHER = ['t', 'u', 'v', 'str', 'vstr', 'concat', 'chr', 'datetime', 'substr', 'strlwr', 'strupr',
    'sqr', 'array', 'range', 'debug', 'warning', 'error', 'filter'];
const VALUE = [...new Set([
    ...reserved.filter((w) => w.category === 'float' || w.category === 'vector').map((w) => w.word),
    ...VALUE_OTHER,
])].filter((w) => !STATEMENT.includes(w)).sort();
const KEYWORD = reserved.map((w) => w.word).filter((w) => !STATEMENT.includes(w) && !DIRECTIVE.includes(w) &&
    !VALUE.includes(w) && !COLOUR.includes(w) && !COLOR.includes(w) && !CHANNEL.includes(w)).sort();

// Top-level statements that open a block but are not schema-checked blocks.
const SCENE = ['background', 'default', 'fog', 'photons', 'radiosity', 'rainbow', 'sky_sphere'];
const blockNames = [...Object.keys(blockDoc.blocks), ...SCENE].sort();
const blockSet = new Set(blockNames);
const itemKeywords = KEYWORD.filter((w) => !blockSet.has(w));

const CONSTANTS = ['clock', 'clock_on', 'no', 'now', 'off', 'on', 'pi', 't', 'tau', 'u', 'v', 'version',
    'x', 'y', 'z', 'yes'];
const BUILTINS = [...new Set(VALUE.filter((w) => !CONSTANTS.includes(w)))].sort();

const longestFirst = (a, b) => b.length - a.length || (a < b ? -1 : a > b ? 1 : 0);
const words = (list) => `\\b(?:${[...new Set(list)].sort(longestFirst).map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`;

const grammar = {
    name: 'POV-Ray',
    scopeName: 'source.pov',
    patterns: [
        { include: '#comment' }, { include: '#string' }, { include: '#directive' }, { include: '#statement' },
        { include: '#colorop' }, { include: '#colorword' }, { include: '#channel' }, { include: '#constant' },
        { include: '#builtin' }, { include: '#block' }, { include: '#item' }, { include: '#number' },
    ],
    repository: {
        comment: { patterns: [
            { name: 'comment.line.double-slash.pov', match: '//[^\\n]*' },
            { name: 'comment.block.pov', match: '/\\*[^*]*\\*+([^/*][^*]*\\*+)*/' },
        ] },
        string: { name: 'string.quoted.double.pov', match: '"([^"\\\\\\n]|\\\\.)*"' },
        directive: { name: 'keyword.control.directive.pov', match: '#\\s*[A-Za-z_]+' },
        statement: { name: 'keyword.control.pov', match: words(STATEMENT) },
        colorop: { name: 'support.function.color.pov', match: words(COLOUR) },
        colorword: { name: 'keyword.other.color.pov', match: words(COLOR) },
        channel: { name: 'constant.other.channel.pov', match: words(CHANNEL) },
        constant: { name: 'constant.language.pov', match: words(CONSTANTS) },
        builtin: { name: 'support.function.builtin.pov', match: words(BUILTINS) },
        block: { name: 'keyword.other.block.pov', match: words(blockNames) },
        item: { name: 'keyword.other.item.pov', match: words(itemKeywords) },
        number: { name: 'constant.numeric.pov', match: '(\\d+\\.?\\d*|\\.\\d+)([eE][+-]?\\d+)?' },
    },
};

const blocks = {};
for (const [name, entry] of Object.entries(blockDoc.blocks))
    blocks[name] = { items: entry.items, ...(entry.nested ? { nested: entry.nested } : {}) };
const snapshot = {
    format: 'pov4-blocks/1',
    comment: 'Legal reserved-word items of each scene-language block; generated by tools/language/vscode.mjs — do not edit.',
    blocks,
};

mkdirSync(join(root, 'extensions/vscode/syntaxes'), { recursive: true });
writeFileSync(join(root, 'extensions/vscode/syntaxes/pov.tmLanguage.json'), `${JSON.stringify(grammar, null, 2)}\n`);
writeFileSync(join(root, 'extensions/vscode/pov4-blocks.json'), `${JSON.stringify(snapshot, null, 2)}\n`);
console.log(`wrote extensions/vscode/syntaxes/pov.tmLanguage.json (${blockNames.length} block keywords, ` +
            `${itemKeywords.length} item keywords, ${BUILTINS.length} builtins)`);
console.log(`wrote extensions/vscode/pov4-blocks.json (${Object.keys(blocks).length} blocks)`);
